# Generated by Django 5.0.4 on 2024-04-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26)),
                ('surname', models.CharField(max_length=26)),
                ('year', models.CharField(max_length=4)),
                ('address', models.CharField(max_length=52)),
            ],
        ),
    ]
